// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IStarkVerifier {
    /// @notice Verifies a Stark proof against public inputs and a trusted root.
    /// @param proof The serialized Stark proof generated by the prover.
    /// @param publicInputs The public inputs (e.g., state root, sequence, gas params) as bytes.
    /// @param trustedRoot The expected Merkle root (appHash) from the trusted state.
    /// @return A boolean indicating if the proof is valid.
    function verify(bytes memory proof, bytes memory publicInputs, bytes32 trustedRoot) external view returns (bool);
}