[package]
name = "uibcp"
version = "0.1.0"
edition = "2021"

[dependencies]
winterfell = "0.6"
winter-air = "0.6"
winter-math = "0.6"
winter-crypto = "0.6"
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }

[build-dependencies]
prost-build = "0.11"

[lib]
name = "uibcp"
path = "src/lib.rs"

[[bin]]
name = "export_poseidon"
path = "scripts/export_poseidon.rs"